### PR TITLE
Handle JSON pointer escape notation, fixes #23

### LINKED ISSUE #23: Error: Couldn't find property ~1 of ...
When `ajv` returns JsonPointers containing `~0` or `~1` replacements (for `~` and `/`), `better-ajv-errors` seems to fail to be able to find the cause of the error:

```text
Couldn't find property ~1 of /paths/~1/GET
Error: Couldn't find property ~1 of /paths/~1/GET
    at pointers.reduce (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/json/get-meta-from-path.js:15:19)
    at Array.reduce (<anonymous>)
    at getMetaFromPath (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/json/get-meta-from-path.js:9:19)
    at AdditionalPropValidationError.getLocation (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/validation-errors/base.js:20:47)
    at AdditionalPropValidationError.getCodeFrame (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/validation-errors/base.js:28:64)
    at AdditionalPropValidationError.print (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/validation-errors/additional-prop.js:25:31)
    at customErrorToText (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/index.js:21:44)
    at Array.map (<anonymous>)
    at exports.default (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/index.js:31:25)
    at schemaValidate (/home/mike/nodejs/oas-kit/packages/oas-validator/index.js:1306:30)
```

### PR DESCRIPTION
**Pull request by MikeRalphson**
As per `TODO` comment.

Tested as fixing the issue, ~~but would appreciate help in writing a new testcase or two to prevent regressions.~~

Tests now copied from https://github.com/torifat/better-ajv-errors/pull/1 hope @ifroz doesn't mind. All passing.

### CODE REVIEW

**Comment by ifroz** [comment]
Sure, go ahead 👍

**Comment by MikeRalphson** [comment]
Thanks @ifroz !

**Comment by P0lip** [comment]
@MikeRalphson @ifroz 
What's the status of this PR? Is there anything I could do to move it forward?

**Comment by ifroz** [comment]
@MikeRalphson @P0lip 
I'd be very glad to see this pulled in. I just rebased this thing, but I'm not sure how to track this properly. 

https://github.com/atlassian/better-ajv-errors/compare/master...ifroz:fix23

Let me know if I can do anything to move it forward!

**Comment by torifat** [comment]
@ifroz Please push your changes and give me a ping.

**Comment by ifroz** [comment]
@torifat please see https://github.com/atlassian/better-ajv-errors/pull/48

**Comment by torifat** [comment]
Merged in #48

**Pull request closed without merging**
